[package]
edition.workspace = true
license.workspace = true
name = "test-vector"
version.workspace = true

[dependencies]
evm-guest = { path = "../guest", default-features = false }
itertools.workspace = true
rand.workspace = true
rand_xoshiro.workspace = true
revm-bytecode = { workspace = true, features = ["parse"] }
revm-context = { workspace = true, features = ["serde"] }
revm-database = { workspace = true, features = ["serde"] }
revm-interpreter.workspace = true
revm-primitives = { workspace = true, features = ["rand"] }
serde_json.workspace = true

[dev-dependencies]
rayon.workspace = true
