[package]
edition.workspace = true
license.workspace = true
name = "test-vector"
version.workspace = true

[dependencies]
itertools.workspace = true
evm-guest = { path = "../guest", default-features = false }
rand.workspace = true
rand_xoshiro.workspace = true
revm-bytecode.workspace = true
revm-interpreter.workspace = true
revm-primitives = { workspace = true, features = ["rand"] }
