[package]
edition = "2021"
name = "evm-guest"
version = "0.1.0"

[dependencies]
revm-context = { workspace = true, features = ["serde"] }
revm-database = { workspace = true, features = ["serde"] }
revm-interpreter.workspace = true
revm-primitives.workspace = true
serde.workspace = true

sp1-zkvm = { workspace = true, optional = true }

[features]
baseline = []
default = ["guest"]
guest = ["dep:sp1-zkvm"]
